### ISSUE TITLE
Similar library

### ISSUE THREAD

**Issue by a3kov** [VictorGaiva/rabbit-stream#2]
I found a similar project for Erlang
https://gitlab.com/evnu/lake
Maybe there's a possibility to join forces and to avoid duplicating efforts ?
Please correct me if I'm missing something :)
Hope this helps..

**Comment by VictorGaiva** [comment]
Hey there.

I saw this client when starting the project, but my intention was to create one fully written in Elixir.

Currently I'm using a code imported from 'rabbitmq' directly, for decoding, but I have the intention of migrating it to Elixir too. 

And also the erlang client hadn't had updates for a while, when I started implementing it.
