### ISSUE TITLE
How to setup TLS

### ISSUE THREAD

**Issue by smahi** [VictorGaiva/rabbit-stream#6]
Hi,
first of all thank you so much for building such awesome library,
i was looking into the official documentation of the library but could not find how to setup TLS!
is it not implemented yet?

Thank again.

**Comment by VictorGaiva** [comment]
I didn't look at this yet but I'm aware of how some other libraries implement it. I'm wrapping up the version 0.3.0 at the moment, and will take a look at how to use TLS as soon as I finish it.

**Comment by smahi** [comment]
Thank you so much for your efforts

**Comment by VictorGaiva** [comment]
Hey, @smahi. TLS Support is now on `main`. I'll improve the documentation this weekend and intend to release `0.4.0` next week.

**Comment by smahi** [comment]
@VictorGaiva
Thank you so much, sir.
